### ISSUE TITLE
Pas les permissions d'executer la commande

### ISSUE THREAD

**Issue by Bukiiee** [souleaub/CSBLink#1]
Hello,

Pour lier son compte ds et son mail CSB, il faut faire la commande /link dans le salon #bots
Petit hic : je n'ai pas les perms d'envoyer des messages sur le serveur (avec d'autres élèves également) ._.

**Comment by souleaub** [comment]
Salut, je viens de mettre a jour les permissions, hésite pas a update si y'a d'autres soucis :)

Ben

**Comment by Bukiiee** [comment]
Super merci
Mntn j'ai les perms mais le /link ne trigger rien du tout :,) il s'envoie simplement comme un message normal

**Comment by souleaub** [comment]
En effet le rôle de base n'avait pas les droits pour les commandes. C'est fix, merci de l'issue !
